# Netlify Build Configuration
# Este archivo le dice a Netlify cómo compilar Flutter

[build]
  command = """
    git clone https://github.com/flutter/flutter.git -b stable --depth 1
    export PATH="$PATH:`pwd`/flutter/bin"
    flutter config --enable-web
    flutter pub get
    flutter build web --release
  """
  publish = "build/web"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
