// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-06WauOcffh8157o5rdPiot99Xpg2tXs',
    appId: '1:655759945651:web:43c379d2e3e4e382b9a5c6',
    messagingSenderId: '655759945651',
    projectId: 'sellora-2xtskv',
    authDomain: 'sellora-2xtskv.firebaseapp.com',
    storageBucket: 'sellora-2xtskv.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhQ63oBN60K9M0Q5OJWUrmOkWOtvH4aog',
    appId: '1:655759945651:android:688c5a7f7cc61965b9a5c6',
    messagingSenderId: '655759945651',
    projectId: 'sellora-2xtskv',
    storageBucket: 'sellora-2xtskv.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzRshc9cs5cAgmhLGBoNnnJ51lCtym_Ak',
    appId: '1:655759945651:ios:c59097d2fe608226b9a5c6',
    messagingSenderId: '655759945651',
    projectId: 'sellora-2xtskv',
    storageBucket: 'sellora-2xtskv.firebasestorage.app',
    androidClientId: '655759945651-qd4j04o332qp1qd7mguo3kajiki48s0r.apps.googleusercontent.com',
    iosClientId: '655759945651-3vbu2pft8madnb7vf510qdraf7tpt4fk.apps.googleusercontent.com',
    iosBundleId: 'com.mycompany.CounterApp',
  );

}