name: Build Flutter Web

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Download Google Fonts
        run: |
          flutter pub run google_fonts:download || echo "Google Fonts download skipped"
        continue-on-error: true

      - name: Build web
        run: flutter build web --release --verbose

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: build/web/
          retention-days: 30
